version: '3.8'

services:
  backend:
    build: ./backend
    container_name: fastapi-backend
    ports:
      - "8000:8000"
    volumes:
      - ./frontend/dist:/app/frontend/dist
    networks:
      - app-network
  frontend:
    build: ./frontend
    container_name: vue-frontend
    ports:
      - "8080:8080"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
